### ISSUE TITLE
加载更多失败的处理

### ISSUE THREAD

**Issue by devinRex** [xtongs/vue-recyclist#3]
首先代码很精彩，收获很多，感谢！
然后我有一个疑问，就是这种无限滚动的形式，采用墓碑的形式去先做占位，然后去请求数据，如果这个时候请求数据失败了应该怎么处理呢？特别是你滑动比较快的时候，下面可能出现了很多墓碑了，如果这个时候去还原可能体验不会太好。

**Comment by xtongs** [comment]
非常好的问题，加载失败的重试和错误处理确实是优化体验必须的，该repo其实只是简单实现了思路，还有很多优化空间。另外，Dom回收列表，比较类似于iOS和安卓开发中的UITableView和ListView。作为Web前端开发者，期望更多浏览器能增加诸如IntersectionObserver这样的支持；或者无限列表的Dom回收工作如果能在浏览器底层实现，自然是最好的。
