### ISSUE TITLE
Grid Version

### ISSUE THREAD

**Issue by ratracegrad** [xtongs/vue-recyclist#6]
Can vue-recyclist be used in a grid format instead of having all items stacked vertically? I want to be able to show multiple items in a row that is responsive based on resize of screen width. So if I have 100 widgets that I want to display with 20 at a time. Each widget is 500px wide. So on a laptop, I can generally display two widgets per row or 1 widget per row on a phone but 3 or 4 widgets on a large screen monitor. So I want to be able to display items horizontally and then wrap to the next row instead of having all the widgets display in one vertical layout. Can this be done with vue-recyclist?

**Comment by xtongs** [comment]
Sorry that responsive grid layout is not supported, because it needs precise dom height for calculation. Since I have no plan for maintaining this repo, you may find other solutions. But this feature request is very interesting, perhaps I will consider refactor this component sometime.
